"""initial schema

Revision ID: 657d88d002f3
Revises: 
Create Date: 2026-03-05 17:39:59.166900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657d88d002f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roboteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roboteer_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('imported_from_sheet_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('weight_class', sa.String(), nullable=False),
    sa.Column('google_sheet_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('setup', 'registration', 'qualifying', 'bracket', 'sub_events', 'complete', name='eventstatus'), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_name', sa.String(), nullable=False),
    sa.Column('roboteer_id', sa.Integer(), nullable=False),
    sa.Column('weapon_type', sa.String(), nullable=True),
    sa.Column('sheet_row_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_source', sa.Enum('sheet', 'upload', 'none', name='imagesource'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roboteer_id'], ['roboteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('is_reserve', sa.Boolean(), nullable=False),
    sa.Column('reserve_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'robot_id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('phase_type', sa.Enum('qualifying', 'bracket', name='phasetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'complete', name='phasestatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('matchup_type', sa.Enum('main', 'sub_event', name='runordermatchuptype'), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format', sa.Enum('two_v_two_team_bracket', name='subeventformat'), nullable=False),
    sa.Column('status', sa.Enum('setup', 'active', 'complete', name='subeventstatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('robot1_id', sa.Integer(), nullable=False),
    sa.Column('robot2_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='matchupstatus'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['robot1_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['robot2_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robot_retirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('retired_robot_id', sa.Integer(), nullable=False),
    sa.Column('replacement_robot_id', sa.Integer(), nullable=True),
    sa.Column('retired_after_phase_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['replacement_robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['retired_after_phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['retired_robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_event_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_event_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('robot1_id', sa.Integer(), nullable=False),
    sa.Column('robot2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robot1_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['robot2_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['sub_event_id'], ['sub_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('points_scored', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchup_id'], ['matchups.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_event_matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_event_id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=True),
    sa.Column('team2_id', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='matchupstatus'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_event_id'], ['sub_events.id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['sub_event_teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['sub_event_teams.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['sub_event_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_event_matchups')
    op.drop_table('results')
    op.drop_table('sub_event_teams')
    op.drop_table('robot_retirements')
    op.drop_table('matchups')
    op.drop_table('sub_events')
    op.drop_table('run_order')
    op.drop_table('phases')
    op.drop_table('event_robots')
    op.drop_table('robots')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('roboteers')
    # ### end Alembic commands ###
