"""add_bracket_round_to_matchups

Revision ID: f1591a03e726
Revises: 657d88d002f3
Create Date: 2026-03-07 15:12:31.265186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1591a03e726'
down_revision: Union[str, Sequence[str], None] = '657d88d002f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchups', sa.Column('bracket_round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchups', 'bracket_round')
    # ### end Alembic commands ###
